// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MapReduceMsg.proto

package itmo.escience.dstorage.agent;

public final class MapReduceMsgProto {
  private MapReduceMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MapReduceMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 count = 1;
    /**
     * <code>required int32 count = 1;</code>
     */
    boolean hasCount();
    /**
     * <code>required int32 count = 1;</code>
     */
    int getCount();

    // required string id = 2;
    /**
     * <code>required string id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 2;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 2;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // required string back_uri = 3;
    /**
     * <code>required string back_uri = 3;</code>
     */
    boolean hasBackUri();
    /**
     * <code>required string back_uri = 3;</code>
     */
    java.lang.String getBackUri();
    /**
     * <code>required string back_uri = 3;</code>
     */
    com.google.protobuf.ByteString
        getBackUriBytes();

    // required string leader_uri = 4;
    /**
     * <code>required string leader_uri = 4;</code>
     */
    boolean hasLeaderUri();
    /**
     * <code>required string leader_uri = 4;</code>
     */
    java.lang.String getLeaderUri();
    /**
     * <code>required string leader_uri = 4;</code>
     */
    com.google.protobuf.ByteString
        getLeaderUriBytes();

    // required string options = 5;
    /**
     * <code>required string options = 5;</code>
     */
    boolean hasOptions();
    /**
     * <code>required string options = 5;</code>
     */
    java.lang.String getOptions();
    /**
     * <code>required string options = 5;</code>
     */
    com.google.protobuf.ByteString
        getOptionsBytes();

    // required bytes data = 6;
    /**
     * <code>required bytes data = 6;</code>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 6;</code>
     */
    com.google.protobuf.ByteString getData();

    // required string session_id = 7;
    /**
     * <code>required string session_id = 7;</code>
     */
    boolean hasSessionId();
    /**
     * <code>required string session_id = 7;</code>
     */
    java.lang.String getSessionId();
    /**
     * <code>required string session_id = 7;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    // required .agent.MapReduceMsg.Action action = 8;
    /**
     * <code>required .agent.MapReduceMsg.Action action = 8;</code>
     */
    boolean hasAction();
    /**
     * <code>required .agent.MapReduceMsg.Action action = 8;</code>
     */
    itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.Action getAction();

    // required string agent_list = 9;
    /**
     * <code>required string agent_list = 9;</code>
     */
    boolean hasAgentList();
    /**
     * <code>required string agent_list = 9;</code>
     */
    java.lang.String getAgentList();
    /**
     * <code>required string agent_list = 9;</code>
     */
    com.google.protobuf.ByteString
        getAgentListBytes();

    // required string name = 10;
    /**
     * <code>required string name = 10;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 10;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 10;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required string proto = 11;
    /**
     * <code>required string proto = 11;</code>
     */
    boolean hasProto();
    /**
     * <code>required string proto = 11;</code>
     */
    java.lang.String getProto();
    /**
     * <code>required string proto = 11;</code>
     */
    com.google.protobuf.ByteString
        getProtoBytes();

    // required string datafile = 12;
    /**
     * <code>required string datafile = 12;</code>
     */
    boolean hasDatafile();
    /**
     * <code>required string datafile = 12;</code>
     */
    java.lang.String getDatafile();
    /**
     * <code>required string datafile = 12;</code>
     */
    com.google.protobuf.ByteString
        getDatafileBytes();
  }
  /**
   * Protobuf type {@code agent.MapReduceMsg}
   */
  public static final class MapReduceMsg extends
      com.google.protobuf.GeneratedMessage
      implements MapReduceMsgOrBuilder {
    // Use MapReduceMsg.newBuilder() to construct.
    private MapReduceMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MapReduceMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MapReduceMsg defaultInstance;
    public static MapReduceMsg getDefaultInstance() {
      return defaultInstance;
    }

    public MapReduceMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MapReduceMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              count_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              id_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              backUri_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              leaderUri_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              options_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              data_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              sessionId_ = input.readBytes();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.Action value = itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.Action.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                action_ = value;
              }
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              agentList_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              name_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              proto_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              datafile_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return itmo.escience.dstorage.agent.MapReduceMsgProto.internal_static_agent_MapReduceMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return itmo.escience.dstorage.agent.MapReduceMsgProto.internal_static_agent_MapReduceMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.class, itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<MapReduceMsg> PARSER =
        new com.google.protobuf.AbstractParser<MapReduceMsg>() {
      public MapReduceMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MapReduceMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MapReduceMsg> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code agent.MapReduceMsg.Action}
     */
    public enum Action
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MAP = 0;</code>
       */
      MAP(0, 0),
      /**
       * <code>REDUCE = 1;</code>
       */
      REDUCE(1, 1),
      /**
       * <code>LEADER = 2;</code>
       */
      LEADER(2, 2),
      ;

      /**
       * <code>MAP = 0;</code>
       */
      public static final int MAP_VALUE = 0;
      /**
       * <code>REDUCE = 1;</code>
       */
      public static final int REDUCE_VALUE = 1;
      /**
       * <code>LEADER = 2;</code>
       */
      public static final int LEADER_VALUE = 2;


      public final int getNumber() { return value; }

      public static Action valueOf(int value) {
        switch (value) {
          case 0: return MAP;
          case 1: return REDUCE;
          case 2: return LEADER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Action>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Action>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Action>() {
              public Action findValueByNumber(int number) {
                return Action.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final Action[] VALUES = values();

      public static Action valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Action(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:agent.MapReduceMsg.Action)
    }

    private int bitField0_;
    // required int32 count = 1;
    public static final int COUNT_FIELD_NUMBER = 1;
    private int count_;
    /**
     * <code>required int32 count = 1;</code>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 count = 1;</code>
     */
    public int getCount() {
      return count_;
    }

    // required string id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private java.lang.Object id_;
    /**
     * <code>required string id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string id = 2;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string back_uri = 3;
    public static final int BACK_URI_FIELD_NUMBER = 3;
    private java.lang.Object backUri_;
    /**
     * <code>required string back_uri = 3;</code>
     */
    public boolean hasBackUri() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string back_uri = 3;</code>
     */
    public java.lang.String getBackUri() {
      java.lang.Object ref = backUri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          backUri_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string back_uri = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBackUriBytes() {
      java.lang.Object ref = backUri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        backUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string leader_uri = 4;
    public static final int LEADER_URI_FIELD_NUMBER = 4;
    private java.lang.Object leaderUri_;
    /**
     * <code>required string leader_uri = 4;</code>
     */
    public boolean hasLeaderUri() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string leader_uri = 4;</code>
     */
    public java.lang.String getLeaderUri() {
      java.lang.Object ref = leaderUri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          leaderUri_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string leader_uri = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLeaderUriBytes() {
      java.lang.Object ref = leaderUri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string options = 5;
    public static final int OPTIONS_FIELD_NUMBER = 5;
    private java.lang.Object options_;
    /**
     * <code>required string options = 5;</code>
     */
    public boolean hasOptions() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string options = 5;</code>
     */
    public java.lang.String getOptions() {
      java.lang.Object ref = options_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          options_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string options = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOptionsBytes() {
      java.lang.Object ref = options_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        options_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes data = 6;
    public static final int DATA_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 6;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required bytes data = 6;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    // required string session_id = 7;
    public static final int SESSION_ID_FIELD_NUMBER = 7;
    private java.lang.Object sessionId_;
    /**
     * <code>required string session_id = 7;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string session_id = 7;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string session_id = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .agent.MapReduceMsg.Action action = 8;
    public static final int ACTION_FIELD_NUMBER = 8;
    private itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.Action action_;
    /**
     * <code>required .agent.MapReduceMsg.Action action = 8;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required .agent.MapReduceMsg.Action action = 8;</code>
     */
    public itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.Action getAction() {
      return action_;
    }

    // required string agent_list = 9;
    public static final int AGENT_LIST_FIELD_NUMBER = 9;
    private java.lang.Object agentList_;
    /**
     * <code>required string agent_list = 9;</code>
     */
    public boolean hasAgentList() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required string agent_list = 9;</code>
     */
    public java.lang.String getAgentList() {
      java.lang.Object ref = agentList_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          agentList_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string agent_list = 9;</code>
     */
    public com.google.protobuf.ByteString
        getAgentListBytes() {
      java.lang.Object ref = agentList_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        agentList_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string name = 10;
    public static final int NAME_FIELD_NUMBER = 10;
    private java.lang.Object name_;
    /**
     * <code>required string name = 10;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required string name = 10;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 10;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string proto = 11;
    public static final int PROTO_FIELD_NUMBER = 11;
    private java.lang.Object proto_;
    /**
     * <code>required string proto = 11;</code>
     */
    public boolean hasProto() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required string proto = 11;</code>
     */
    public java.lang.String getProto() {
      java.lang.Object ref = proto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          proto_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string proto = 11;</code>
     */
    public com.google.protobuf.ByteString
        getProtoBytes() {
      java.lang.Object ref = proto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string datafile = 12;
    public static final int DATAFILE_FIELD_NUMBER = 12;
    private java.lang.Object datafile_;
    /**
     * <code>required string datafile = 12;</code>
     */
    public boolean hasDatafile() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required string datafile = 12;</code>
     */
    public java.lang.String getDatafile() {
      java.lang.Object ref = datafile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          datafile_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string datafile = 12;</code>
     */
    public com.google.protobuf.ByteString
        getDatafileBytes() {
      java.lang.Object ref = datafile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        datafile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      count_ = 0;
      id_ = "";
      backUri_ = "";
      leaderUri_ = "";
      options_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
      sessionId_ = "";
      action_ = itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.Action.MAP;
      agentList_ = "";
      name_ = "";
      proto_ = "";
      datafile_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBackUri()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLeaderUri()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOptions()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSessionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAgentList()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProto()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDatafile()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, count_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getBackUriBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getLeaderUriBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getOptionsBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, data_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeEnum(8, action_.getNumber());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getAgentListBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getNameBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getProtoBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getDatafileBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, count_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getBackUriBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getLeaderUriBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getOptionsBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, data_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, action_.getNumber());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getAgentListBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getNameBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getProtoBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getDatafileBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code agent.MapReduceMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return itmo.escience.dstorage.agent.MapReduceMsgProto.internal_static_agent_MapReduceMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return itmo.escience.dstorage.agent.MapReduceMsgProto.internal_static_agent_MapReduceMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.class, itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.Builder.class);
      }

      // Construct using agent.MapReduceMsgProto.MapReduceMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        backUri_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        leaderUri_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        options_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        sessionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        action_ = itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.Action.MAP;
        bitField0_ = (bitField0_ & ~0x00000080);
        agentList_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        proto_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        datafile_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return itmo.escience.dstorage.agent.MapReduceMsgProto.internal_static_agent_MapReduceMsg_descriptor;
      }

      public itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg getDefaultInstanceForType() {
        return itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.getDefaultInstance();
      }

      public itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg build() {
        itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg buildPartial() {
        itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg result = new itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.count_ = count_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.backUri_ = backUri_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.leaderUri_ = leaderUri_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.options_ = options_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.agentList_ = agentList_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.proto_ = proto_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.datafile_ = datafile_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg) {
          return mergeFrom((itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg other) {
        if (other == itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.getDefaultInstance()) return this;
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (other.hasId()) {
          bitField0_ |= 0x00000002;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasBackUri()) {
          bitField0_ |= 0x00000004;
          backUri_ = other.backUri_;
          onChanged();
        }
        if (other.hasLeaderUri()) {
          bitField0_ |= 0x00000008;
          leaderUri_ = other.leaderUri_;
          onChanged();
        }
        if (other.hasOptions()) {
          bitField0_ |= 0x00000010;
          options_ = other.options_;
          onChanged();
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasSessionId()) {
          bitField0_ |= 0x00000040;
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasAgentList()) {
          bitField0_ |= 0x00000100;
          agentList_ = other.agentList_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000200;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasProto()) {
          bitField0_ |= 0x00000400;
          proto_ = other.proto_;
          onChanged();
        }
        if (other.hasDatafile()) {
          bitField0_ |= 0x00000800;
          datafile_ = other.datafile_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCount()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        if (!hasBackUri()) {
          
          return false;
        }
        if (!hasLeaderUri()) {
          
          return false;
        }
        if (!hasOptions()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        if (!hasSessionId()) {
          
          return false;
        }
        if (!hasAction()) {
          
          return false;
        }
        if (!hasAgentList()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasProto()) {
          
          return false;
        }
        if (!hasDatafile()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 count = 1;
      private int count_ ;
      /**
       * <code>required int32 count = 1;</code>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 count = 1;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>required int32 count = 1;</code>
       */
      public Builder setCount(int value) {
        bitField0_ |= 0x00000001;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 count = 1;</code>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0;
        onChanged();
        return this;
      }

      // required string id = 2;
      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string id = 2;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 2;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 2;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }

      // required string back_uri = 3;
      private java.lang.Object backUri_ = "";
      /**
       * <code>required string back_uri = 3;</code>
       */
      public boolean hasBackUri() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string back_uri = 3;</code>
       */
      public java.lang.String getBackUri() {
        java.lang.Object ref = backUri_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          backUri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string back_uri = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBackUriBytes() {
        java.lang.Object ref = backUri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          backUri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string back_uri = 3;</code>
       */
      public Builder setBackUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        backUri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string back_uri = 3;</code>
       */
      public Builder clearBackUri() {
        bitField0_ = (bitField0_ & ~0x00000004);
        backUri_ = getDefaultInstance().getBackUri();
        onChanged();
        return this;
      }
      /**
       * <code>required string back_uri = 3;</code>
       */
      public Builder setBackUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        backUri_ = value;
        onChanged();
        return this;
      }

      // required string leader_uri = 4;
      private java.lang.Object leaderUri_ = "";
      /**
       * <code>required string leader_uri = 4;</code>
       */
      public boolean hasLeaderUri() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string leader_uri = 4;</code>
       */
      public java.lang.String getLeaderUri() {
        java.lang.Object ref = leaderUri_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          leaderUri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string leader_uri = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLeaderUriBytes() {
        java.lang.Object ref = leaderUri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          leaderUri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string leader_uri = 4;</code>
       */
      public Builder setLeaderUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        leaderUri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string leader_uri = 4;</code>
       */
      public Builder clearLeaderUri() {
        bitField0_ = (bitField0_ & ~0x00000008);
        leaderUri_ = getDefaultInstance().getLeaderUri();
        onChanged();
        return this;
      }
      /**
       * <code>required string leader_uri = 4;</code>
       */
      public Builder setLeaderUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        leaderUri_ = value;
        onChanged();
        return this;
      }

      // required string options = 5;
      private java.lang.Object options_ = "";
      /**
       * <code>required string options = 5;</code>
       */
      public boolean hasOptions() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string options = 5;</code>
       */
      public java.lang.String getOptions() {
        java.lang.Object ref = options_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          options_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string options = 5;</code>
       */
      public com.google.protobuf.ByteString
          getOptionsBytes() {
        java.lang.Object ref = options_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          options_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string options = 5;</code>
       */
      public Builder setOptions(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        options_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string options = 5;</code>
       */
      public Builder clearOptions() {
        bitField0_ = (bitField0_ & ~0x00000010);
        options_ = getDefaultInstance().getOptions();
        onChanged();
        return this;
      }
      /**
       * <code>required string options = 5;</code>
       */
      public Builder setOptionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        options_ = value;
        onChanged();
        return this;
      }

      // required bytes data = 6;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 6;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bytes data = 6;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 6;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 6;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000020);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // required string session_id = 7;
      private java.lang.Object sessionId_ = "";
      /**
       * <code>required string session_id = 7;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string session_id = 7;</code>
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string session_id = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string session_id = 7;</code>
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string session_id = 7;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>required string session_id = 7;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        sessionId_ = value;
        onChanged();
        return this;
      }

      // required .agent.MapReduceMsg.Action action = 8;
      private itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.Action action_ = itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.Action.MAP;
      /**
       * <code>required .agent.MapReduceMsg.Action action = 8;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required .agent.MapReduceMsg.Action action = 8;</code>
       */
      public itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.Action getAction() {
        return action_;
      }
      /**
       * <code>required .agent.MapReduceMsg.Action action = 8;</code>
       */
      public Builder setAction(itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.Action value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .agent.MapReduceMsg.Action action = 8;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000080);
        action_ = itmo.escience.dstorage.agent.MapReduceMsgProto.MapReduceMsg.Action.MAP;
        onChanged();
        return this;
      }

      // required string agent_list = 9;
      private java.lang.Object agentList_ = "";
      /**
       * <code>required string agent_list = 9;</code>
       */
      public boolean hasAgentList() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required string agent_list = 9;</code>
       */
      public java.lang.String getAgentList() {
        java.lang.Object ref = agentList_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          agentList_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string agent_list = 9;</code>
       */
      public com.google.protobuf.ByteString
          getAgentListBytes() {
        java.lang.Object ref = agentList_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          agentList_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string agent_list = 9;</code>
       */
      public Builder setAgentList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        agentList_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string agent_list = 9;</code>
       */
      public Builder clearAgentList() {
        bitField0_ = (bitField0_ & ~0x00000100);
        agentList_ = getDefaultInstance().getAgentList();
        onChanged();
        return this;
      }
      /**
       * <code>required string agent_list = 9;</code>
       */
      public Builder setAgentListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        agentList_ = value;
        onChanged();
        return this;
      }

      // required string name = 10;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 10;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required string name = 10;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 10;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 10;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 10;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000200);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 10;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        name_ = value;
        onChanged();
        return this;
      }

      // required string proto = 11;
      private java.lang.Object proto_ = "";
      /**
       * <code>required string proto = 11;</code>
       */
      public boolean hasProto() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required string proto = 11;</code>
       */
      public java.lang.String getProto() {
        java.lang.Object ref = proto_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          proto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string proto = 11;</code>
       */
      public com.google.protobuf.ByteString
          getProtoBytes() {
        java.lang.Object ref = proto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          proto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string proto = 11;</code>
       */
      public Builder setProto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        proto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string proto = 11;</code>
       */
      public Builder clearProto() {
        bitField0_ = (bitField0_ & ~0x00000400);
        proto_ = getDefaultInstance().getProto();
        onChanged();
        return this;
      }
      /**
       * <code>required string proto = 11;</code>
       */
      public Builder setProtoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        proto_ = value;
        onChanged();
        return this;
      }

      // required string datafile = 12;
      private java.lang.Object datafile_ = "";
      /**
       * <code>required string datafile = 12;</code>
       */
      public boolean hasDatafile() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required string datafile = 12;</code>
       */
      public java.lang.String getDatafile() {
        java.lang.Object ref = datafile_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          datafile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string datafile = 12;</code>
       */
      public com.google.protobuf.ByteString
          getDatafileBytes() {
        java.lang.Object ref = datafile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          datafile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string datafile = 12;</code>
       */
      public Builder setDatafile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        datafile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string datafile = 12;</code>
       */
      public Builder clearDatafile() {
        bitField0_ = (bitField0_ & ~0x00000800);
        datafile_ = getDefaultInstance().getDatafile();
        onChanged();
        return this;
      }
      /**
       * <code>required string datafile = 12;</code>
       */
      public Builder setDatafileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        datafile_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:agent.MapReduceMsg)
    }

    static {
      defaultInstance = new MapReduceMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:agent.MapReduceMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_MapReduceMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_agent_MapReduceMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022MapReduceMsg.proto\022\005agent\"\234\002\n\014MapReduc" +
      "eMsg\022\r\n\005count\030\001 \002(\005\022\n\n\002id\030\002 \002(\t\022\020\n\010back_" +
      "uri\030\003 \002(\t\022\022\n\nleader_uri\030\004 \002(\t\022\017\n\007options" +
      "\030\005 \002(\t\022\014\n\004data\030\006 \002(\014\022\022\n\nsession_id\030\007 \002(\t" +
      "\022*\n\006action\030\010 \002(\0162\032.agent.MapReduceMsg.Ac" +
      "tion\022\022\n\nagent_list\030\t \002(\t\022\014\n\004name\030\n \002(\t\022\r" +
      "\n\005proto\030\013 \002(\t\022\020\n\010datafile\030\014 \002(\t\")\n\006Actio" +
      "n\022\007\n\003MAP\020\000\022\n\n\006REDUCE\020\001\022\n\n\006LEADER\020\002B\032\n\005ag" +
      "entB\021MapReduceMsgProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_agent_MapReduceMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_agent_MapReduceMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_agent_MapReduceMsg_descriptor,
              new java.lang.String[] { "Count", "Id", "BackUri", "LeaderUri", "Options", "Data", "SessionId", "Action", "AgentList", "Name", "Proto", "Datafile", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
